import type { Metadata } from "next";
import { ClerkProvider } from '@clerk/nextjs'
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "./(routes)/(root)/components";


const spaceGrotesk = Space_Grotesk({
  variable : "--font-space-grotesk",
  subsets : ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="es">
        <body className={`${spaceGrotesk.variable} antialiased`}>
          <SidebarProvider>
            <AppSidebar />
            <main className="flex-1">{children}</main>
          </SidebarProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
